### ISSUE TITLE
v0.7.0 dependencies change breaks fastlane's google play upload action

### ISSUE THREAD

**Issue by Panajev** [firebase/fastlane-plugin-firebase_app_distribution#335]
### Issue Description

The current 0.7.0 release of the plugin is breaking our CI pipelines since it is forcing Fastlane to use the wrong version of the google dependency:

<img width="505" alt="Screenshot 2023-08-02 at 16 44 31" src="https://github.com/firebase/fastlane-plugin-firebase_app_distribution/assets/562991/16773536-7b4f-48c4-9a32-6f45789491b8">

--> causing: https://github.com/fastlane/fastlane/issues/19208

> unknown keyword: :changes_not_sent_for_review
[...]
> [17:14:19]: fastlane finished with errors
> 
> Looking for related GitHub issues on fastlane/fastlane...
> 
> ➡️  supply - unknown keyword: changes_not_sent_for_review
>     https://github.com/fastlane/fastlane/issues/19208 [closed] 7 💬
>     10 Jan 2022

##### Configuration

N/A it is not this action that fails, but another part of fastlane because of this plugin's dependencies change.

##### Complete verbose output

```
[17:13:55]: ************** Uploading to Play Store! *************
[17:13:55]: Push directly to track without rollout...
[17:13:55]: options[:release_status] = draft
[17:13:55]: ----------------------------------
[17:13:55]: --- Step: upload_to_play_store ---
[17:13:55]: ----------------------------------

+------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                Summary for supply 2.214.0                                                                                 |
+------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| json_key                           | fastlane/nps-fastlane-google-play_co.json                                                                                                |
| track                              | internal                                                                                                                                             |
| package_name                       | com.co.app_built_                                                                                                                            |
| skip_upload_metadata               | true                                                                                                                                                 |
| skip_upload_changelogs             | true                                                                                                                                                 |
| skip_upload_images                 | true                                                                                                                                                 |
| skip_upload_screenshots            | true                                                                                                                                                 |
| skip_upload_apk                    | true                                                                                                                                                 |
| release_status                     | draft                                                                                                                                                |
| validate_only                      | false                                                                                                                                                |
| aab                                | buildProj/app/build/outputs/bundle/app_built_Release/app-app_built_-release.aab |
| skip_upload_aab                    | false                                                                                                                                                |
| track_promote_release_status       | completed                                                                                                                                            |
| check_superseded_tracks            | false                                                                                                                                                |
| timeout                            | 300                                                                                                                                                  |
| deactivate_on_promote              | true                                                                                                                                                 |
| changes_not_sent_for_review        | false                                                                                                                                                |
| rescue_changes_not_sent_for_review | true                                                                                                                                                 |
| ack_bundle_installation_warning    | false                                                                                                                                                |
+------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------+

[17:13:56]: Preparing aab at path 'buildProj/app/build/outputs/bundle/app_built_Release/app-app_built_-release.aab' for upload...
[17:14:18]: Updating track 'internal'...
[17:14:19]: Uploading all changes to Google Play...
+-------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                          Lane Context                                                                                          |
+-------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                    | android                                                                                                                                                  |
| PLATFORM_NAME                       | android                                                                                                                                                  |
| LANE_NAME                           | android deployInternal                                                                                                                                   |
| GRADLE_BUILD_TYPE                   | Release                                                                                                                                                  |
| GRADLE_ALL_APK_OUTPUT_PATHS         | []                                                                                                                                                       |
| GRADLE_ALL_AAB_OUTPUT_PATHS         | ["buildProj/app/build/outputs/bundle/app_built_Release/app-app_built_-release.aab"] |
| GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS | []                                                                                                                                                       |
| GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS | ["buildProj/app/build/outputs/mapping/app_built_Release/mapping.txt"]                  |
| GRADLE_AAB_OUTPUT_PATH              | buildProj/app/build/outputs/bundle/app_built_Release/app-app_built_-release.aab     |
| GRADLE_MAPPING_TXT_OUTPUT_PATH      | buildProj/app/build/outputs/mapping/app_built_Release/mapping.txt                      |
+-------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
[17:14:19]: unknown keyword: :changes_not_sent_for_review

+------+--------------------------------------------------------------+-------------+
|                                 fastlane summary                                  |
+------+--------------------------------------------------------------+-------------+
| Step | Action                                                       | Time (in s) |
+------+--------------------------------------------------------------+-------------+
| 1    | git_branch                                                   | 0           |
| 2    | git log -1 --pretty=format:%H                                | 0           |
| 3    | date +%Y-%m-%d_%H:%M:%S                                      | 0           |
| 4    | default_platform                                             | 0           |
| 5    | Switch to android cleanGradleProject lane                    | 0           |
| 6    | clean                                                        | 3           |
| 7    | cleanBuild                                                   | 2           |
| 8    | Switch to android beta lane                                  | 0           |
| 9    | bundleapp_built_Release                                   | 17          |
| 10   | Switch to android tagBuildReleaseApp lane                    | 0           |
| 11   | Switch to android tagRemove lane                             | 0           |
| 12   |                                                              | 1           |
|      |     cd "machinefolder- |             |
| 13   | git_tag_exists                                               | 0           |
| 14   |                                                              | 2           |
|      |       cd "machinefolder/build-np-N |             |
| 15   |                                                              | 3           |
|      |     cd "machinefolder- |             |
| 16   | Switch to android uploadOrPromoteGooglePlayBuild lane        | 0           |
| 💥   | upload_to_play_store                                         | 23          |
+------+--------------------------------------------------------------+-------------+

[17:14:19]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  supply - unknown keyword: changes_not_sent_for_review
    https://github.com/fastlane/fastlane/issues/19208 [closed] 7 💬
    10 Jan 2022

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (buildProj/vendor/bundle/ruby/3.1.0/bin/fastlane)
buildProj/vendor/bundle/ruby/3.1.0/gems/google-api-client-0.53.0/generated/google/apis/androidpublisher_v3/service.rb:72:in `commit_edit': \e[31m[!] unknown keyword: :changes_not_sent_for_review\e[0m (ArgumentError)
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/supply/lib/supply/client.rb:167:in `block in commit_current_edit!'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/supply/lib/supply/client.rb:81:in `call_google_api'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/supply/lib/supply/client.rb:165:in `commit_current_edit!'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/supply/lib/supply/uploader.rb:43:in `perform_upload'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:614:in `block (2 levels) in parsing_binding'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:516:in `submitToPlay'
	from Fastfile:432:in `block (2 levels) in parsing_binding'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/bin/fastlane:23:in `<top (required)>'
	from buildProj/vendor/bundle/ruby/3.1.0/bin/fastlane:25:in `load'
	from buildProj/vendor/bundle/ruby/3.1.0/bin/fastlane:25:in `<top (required)>'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:58:in `load'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:23:in `run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli.rb:492:in `exec'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli.rb:34:in `dispatch'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli.rb:28:in `start'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/exe/bundle:37:in `block in <top (required)>'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/exe/bundle:29:in `<top (required)>'
	from /cmpuser/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
	from /cmpuser/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
buildProj/vendor/bundle/ruby/3.1.0/gems/google-api-client-0.53.0/generated/google/apis/androidpublisher_v3/service.rb:72:in `commit_edit': unknown keyword: :changes_not_sent_for_review (ArgumentError)
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/supply/lib/supply/client.rb:167:in `block in commit_current_edit!'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/supply/lib/supply/client.rb:81:in `call_google_api'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/supply/lib/supply/client.rb:165:in `commit_current_edit!'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/supply/lib/supply/uploader.rb:43:in `perform_upload'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:614:in `block (2 levels) in parsing_binding'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:516:in `submitToPlay'
	from Fastfile:432:in `block (2 levels) in parsing_binding'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/fastlane-2.214.0/bin/fastlane:23:in `<top (required)>'
	from buildProj/vendor/bundle/ruby/3.1.0/bin/fastlane:25:in `load'
	from buildProj/vendor/bundle/ruby/3.1.0/bin/fastlane:25:in `<top (required)>'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:58:in `load'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli/exec.rb:23:in `run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli.rb:492:in `exec'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli.rb:34:in `dispatch'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/cli.rb:28:in `start'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/exe/bundle:37:in `block in <top (required)>'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from buildProj/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.17/exe/bundle:29:in `<top (required)>'
	from /cmpuser/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
	from /cmpuser/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
```

##### Environment

| Library     | Version |
| ----------- | ----------- |
| fastlane | 2.214.0 |
| fastlane-plugin-firebase_app_distribution | 0.7.0 |

**Comment by lfkellogg** [comment]
Version `0.7.1` removes the dependency on `google-api-client`. Please update and let me know if the issue is resolve for you, thaks!

**Comment by Panajev** [comment]
Seems to work, updated a branch and made a release and it seems to have uploaded to Google Play and Firebase ok :)!

**Comment by lfkellogg** [comment]
Great, thanks!
