### ISSUE TITLE
Show response details when Google APIs requests return errors even in non-debug mode

### ISSUE THREAD

**Issue by vbuberen** [firebase/fastlane-plugin-firebase_app_distribution#374]
### Issue Description

A few days ago I was setting up the Firebase App Distribution in one of projects where I didn't have a full control of the setup, so I had to ask another person with all the necessary access levels to create `firebase-app-distribution-service-account.json` for this project. After getting it ready I proceeded with lane modification and test runs only to see errors with not that informative output:

<details>
<summary>Default plugin output</summary>

```
[14:39:08]: Called from Fastfile at line 96
[14:39:08]: ```
[14:39:08]:     95:	
[14:39:08]:  => 96:	      firebase_app_distribution(
[14:39:08]:     97:	        app: ENV["FIREBASE_APP_ID"],
[14:39:08]:     98:	        service_credentials_file: "./firebase-app-distribution-service-account.json",
[14:39:08]: ```
[14:39:08]: Invalid request

+-------------------------------------------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | ensure_env_vars            | 0           |
| 2    | changelog_from_git_commits | 0           |
| 💥   | firebase_app_distribution  | 3           |
+------+----------------------------+-------------+

[14:39:08]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  android - Invalid request
    https://github.com/fastlane/fastlane/issues/21662 [open] 21 💬
    3 weeks ago

➡️  android - [!] Invalid request (Google::Apis::ClientError)
    https://github.com/fastlane/fastlane/issues/22044 [open] 5 💬
    3 weeks ago

➡️  Google Api Error: Invalid request - APK has been signed with a different certificate to previous APKs.
    https://github.com/fastlane/fastlane/issues/22244 [open] 0 💬
bundler: failed to load command: fastlane (/home/ec2-user/.rvm/gems/ruby-3.0.0/bin/fastlane)
/home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:244:in `check_status': \e[31m[!] Invalid request\e[0m (Google::Apis::ClientError)
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:207:in `process_response'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:326:in `execute_once'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:131:in `block (2 levels) in do_retry'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:128:in `block in do_retry'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:118:in `do_retry'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:109:in `execute'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/base_service.rb:418:in `execute_or_queue_command'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/base_service.rb:265:in `http'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-plugin-firebase_app_distribution-0.9.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:285:in `upload_binary'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-plugin-firebase_app_distribution-0.9.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:59:in `run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:96:in `block (2 levels) in parsing_binding'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/bin/fastlane:23:in `<top (required)>'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/bin/fastlane:23:in `load'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/bin/fastlane:23:in `<top (required)>'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `load'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in `run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in `exec'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `load'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>'
/home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:244:in `check_status': Invalid request (Google::Apis::ClientError)
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:207:in `process_response'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:326:in `execute_once'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:131:in `block (2 levels) in do_retry'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:128:in `block in do_retry'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:118:in `do_retry'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/http_command.rb:109:in `execute'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/base_service.rb:418:in `execute_or_queue_command'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/google-apis-core-0.11.3/lib/google/apis/core/base_service.rb:265:in `http'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-plugin-firebase_app_distribution-0.9.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:285:in `upload_binary'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-plugin-firebase_app_distribution-0.9.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:59:in `run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:96:in `block (2 levels) in parsing_binding'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane.rb:41:in `call'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/command_line_handler.rb:34:in `handle'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:363:in `run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/fastlane-2.225.0/bin/fastlane:23:in `<top (required)>'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/bin/fastlane:23:in `load'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/bin/fastlane:23:in `<top (required)>'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `load'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in `run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in `exec'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `load'
	from /home/ec2-user/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>'
    4 weeks ago

and 5[79](https://github.com/sportalliance/spa-mobile/actions/runs/11500470151/job/32014531062#step:13:80) more at: https://github.com/fastlane/fastlane/search?q=Invalid%20request&type=Issues&utf8=✓

Error: Process completed with exit code 1.
```

</details>

The issue itself turned out to be the missing permissions, so Google API returned 403 with `The caller does not have permission` message and `PERMISSION_DENIED` status. I was able to see this response only after adding `Google::Apis.logger.level = Logger::DEBUG` in the lane before running `firebase_app_distribution()`. Note, that the default output which I shared above doesn't have any clues that could point to the reason of the error. 
Based on such experience and some wasted time before finding out how to get the detailed response I believe that the default output for Google API errors should show response details (message and status) even in non debug mode, so it will be possible to identify the problem faster.

Before opening this issue I searched if there were similar ones here and it seems there was such idea as described in https://github.com/firebase/fastlane-plugin-firebase_app_distribution/issues/132 but it looks like it was never implemented.

##### Configuration
It doesn't really matter in this case, but still, here it is:

```
firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        service_credentials_file: "./firebase-app-distribution-service-account.json",
        groups: "all",
        release_notes: changelog,
        android_artifact_type: "APK",
        android_artifact_path: apk_output_path,
      )
```

##### Complete verbose output
```
D, [2024-10-25T17:24:15.670205 #3256] DEBUG -- : Sending HTTP post https://firebaseappdistribution.googleapis.com/upload/v1/projects/*project_id*/apps/*Firebase_app_id*/releases:upload?
D, [2024-10-25T17:24:25.957520 #3256] DEBUG -- : 403
D, [2024-10-25T17:24:25.962357 #3256] DEBUG -- : #<HTTP::Message:0x0000000104b2a4d0 @http_body=#<HTTP::Message::Body:0x0000000104b2a3e0 @body="{\n" + "  \"error\": {\n" + "    \"code\": 403,\n" + "    \"message\": \"The caller does not have permission\",\n" + "    \"status\": \"PERMISSION_DENIED\"\n" + "  }\n" + "}\n", @chunk_size=nil, @positions=nil, @size=0>, @http_header=#<HTTP::Message::Headers:0x0000000104ccd990 @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @body_size=0, @body_type=nil, @chunked=false, @dumped=false, @header_item=[["Vary", "Origin"], ["Vary", "X-Origin"], ["Vary", "Referer"], ["Content-Type", "application/json; charset=UTF-8"], ["X-GUploader-UploadID", "****"], ["Content-Length", "126"], ["Date", "Fri, 25 Oct 2024 14:24:25 GMT"], ["Server", "UploadServer"], ["Alt-Svc", "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"]], @http_version="1.1", @is_request=false, @reason_phrase="Forbidden", @request_absolute_uri=nil, @request_method="POST", @request_query=nil, @request_uri=#<Addressable::URI:0x1270 URI:https://firebaseappdistribution.googleapis.com/upload/v1/projects/*project_id*/apps/*Firebase_app_id*/releases:upload?>, @status_code=403>, @peer_cert=#<OpenSSL::X509::Certificate subject=#<OpenSSL::X509::Name CN=upload.video.google.com>, issuer=#<OpenSSL::X509::Name CN=WR2,O=Google Trust Services,C=US>, serial=#<OpenSSL::BN 249523738985507380678070046713553759211>, not_before=2024-10-07 08:25:41 UTC, not_after=2024-12-30 08:25:40 UTC>, @previous=nil>
D, [2024-10-25T17:24:25.962521 #3256] DEBUG -- : Caught error Invalid request
D, [2024-10-25T17:24:25.964177 #3256] DEBUG -- : Error - #<Google::Apis::ClientError: Invalid request status_code: 403 header: #<HTTP::Message::Headers:0x00000001067dff08 @http_version="1.1", @body_size=0, @chunked=false, @request_method="POST", @request_uri=#<Addressable::URI:0x1270 URI:https://firebaseappdistribution.googleapis.com/upload/v1/projects/*project_id*/apps/*Firebase_app_id*/releases:upload?>, @request_query=nil, @request_absolute_uri=nil, @status_code=403, @reason_phrase="Forbidden", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Vary", "Origin"], ["Vary", "X-Origin"], ["Vary", "Referer"], ["Content-Type", "application/json; charset=UTF-8"], ["X-GUploader-UploadID", "****"], ["Content-Length", "126"], ["Date", "Fri, 25 Oct 2024 14:24:25 GMT"], ["Server", "UploadServer"], ["Alt-Svc", "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"]], @dumped=false> body: "{\n  \"error\": {\n    \"code\": 403,\n    \"message\": \"The caller does not have permission\",\n    \"status\": \"PERMISSION_DENIED\"\n  }\n}\n">
```

##### Environment
Both CI and local. It doesn't matter for this case.

| Library     | Version |
| ----------- | ----------- |
| fastlane | 2.225.0 |
| fastlane-plugin-firebase_app_distribution | 0.9.1 |

**Comment by kaibolay** [comment]
This released in a few days.

**Comment by vbuberen** [comment]
Awesome news! Thank you.
